node {
  stage('Build Tasks') {
      openshift.withCluster() {
          openshift.withProject("sandbox") {
              openshift.selector("bc", "wingnut").startBuild("--wait=true")
      }
    }
  }
}