---
- name: Deploy Wingnut
  hosts: wingnut
  remote_user: pi
  gather_facts: true
  tasks:
    - name: Ensure chrony is installed
      apt:
        pkg: chrony
      become: yes
    - name: Ensure Redis is present
      apt:
        pkg: redis-server
      become: yes
    - name: Ensure Redis is started
      service:
        name: redis-server
        state: started
        enabled: yes
    - name: Checkout wingnut git repo
      ansible.builtin.git:
        repo: https://github.com/kringen/wingnut.git
        dest: /home/pi/wingnut
    - name: Install required python packages
      pip:
        requirements: /home/pi/wingnut/requirements.txt
    - name: install wingnut systemd unit file
      ansible.builtin.copy: 
        src: /home/pi/wingnut/systemd/wingnut.j2 
        dest: /etc/systemd/system/wingnut.service
        remote_src: yes
        owner: root
        group: root
        mode: '0644'
      become: yes
    - name: start wingnut
      systemd: 
        state: started
        enabled: yes 
        name: wingnut 
        daemon_reload: yes
      become: yes
    - name: install wingnut-ui systemd unit file
      ansible.builtin.copy: 
        src: /home/pi/wingnut/systemd/wingnut-ui.j2 
        dest: /etc/systemd/system/wingnut-ui.service
        remote_src: yes
        owner: root
        group: root
        mode: '0644'
      become: yes
    - name: start wingnut-ui
      systemd: 
        state: started
        enabled: yes 
        name: wingnut-ui 
        daemon_reload: yes
      become: yes
      
