---
- name: Deploy Wingnut
  hosts: wingnut
  remote_user: pi
  gather_facts: true
  tasks:
    - name: Ensure chrony is installed
      apt:
        pkg: chrony
      become: yes
    - name: Ensure Redis is present
      apt:
        pkg: redis-server
      become: yes
    - name: Ensure Redis is started
      service:
        name: redis-server
        state: started
        enabled: yes
    - name: Checkout wingnut git repo
      ansible.builtin.git:
        repo: https://github.com/kringen/wingnut.git
        dest: /home/pi/wingnut
    - name: Install required python packages
      pip:
        requirements: /home/pi/wingnut/requirements.txt
    - name: install myservice systemd unit file
      template: 
        src: /home/pi/wingnut/systemd/wingnut.j2 
        dest: /etc/systemd/system/wingnut.service
        remore_src: yes
    - name: start wingnut
      systemd: 
        state: started 
        name: wingnut 
        daemon_reload: yes
      
